name: RpgPlus
version: VERSION

main: de.craften.plugins.rpgplus.RpgPlus

depend: [Citizens]
softdepend: [NoteBlockAPI, PlayerDataStore]

commands:
  rpgplus:
    description: RpgPlus command
    permission: rpgplus.manage

permissions:
  rpgplus.scripting.notifyerrors:
    description: Players with this permission are notified on script errors and get a stacktrace.
    default: op
  rpgplus.manage:
    description: Players with this permission may use any RpgPlus command (i.e. reloading).
    default: op